# -*- coding: utf-8 -*-
"""calclator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15p9Kf64Z_drZ-dBEePqxZfbjH85yLBd9
"""

# Simple Calculator

# Function to perform calculation
def calculate(num1, num2, operation):
    if operation == '+':
        return num1 + num2
    elif operation == '-':
        return num1 - num2
    elif operation == '*':
        return num1 * num2
    elif operation == '/':
        if num2 == 0:
            return "Error! Division by zero."
        return num1 / num2
    else:
        return "Invalid operation!"

# Main function
def calculator():
    print("Welcome to the Simple Calculator")

    try:
        # Get user input for numbers
        num1 = float(input("Enter the first number: "))
        num2 = float(input("Enter the second number: "))
    except ValueError:
        print("Invalid input! Please enter valid numbers.")
        return

    # Get user input for operation
    print("Choose an operation: +, -, *, /")
    operation = input("Enter the operation: ")

    # Perform the calculation and display the result
    result = calculate(num1, num2, operation)
    print(f"The result of {num1} {operation} {num2} is: {result}")

# Run the calculator
if __name__ == "__main__":
    calculator()