# -*- coding: utf-8 -*-
"""generate_password.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OI4108s8mA5G07mWxqzwNT7C-z7mC7mT
"""

import random
import string

# Function to generate a password
def generate_password(length):
    if length < 4:
        return "Password length should be at least 4 to ensure complexity."

    # Define the characters to use: letters, digits, and special characters
    characters = string.ascii_letters + string.digits + string.punctuation

    # Generate a random password
    password = ''.join(random.choice(characters) for i in range(length))

    return password

# Main function
def password_generator():
    print("Welcome to the Password Generator!")

    try:
        # Get user input for password length
        length = int(input("Enter the desired length of the password (minimum 4): "))
    except ValueError:
        print("Invalid input! Please enter a valid number.")
        return

    # Generate and display the password
    password = generate_password(length)
    print(f"Generated Password: {password}")

# Run the password generator
if __name__ == "__main__":
    password_generator()