# -*- coding: utf-8 -*-
"""to-do list.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1etnBkXN6JNXllrojdH5D4yi_-RLi5yYd
"""

import json
import os

TODO_FILE = 'todo_list.json'

# Load the to-do list from a file or return an empty list if the file doesn't exist
def load_todos():
    if not os.path.exists(TODO_FILE):
        return []
    with open(TODO_FILE, 'r') as file:
        return json.load(file)

# Save the to-do list to a file
def save_todos(todos):
    with open(TODO_FILE, 'w') as file:
        json.dump(todos, file, indent=4)

# Add a new task to the to-do list
def add_todo():
    task = input("Enter the task: ").strip()
    if task:
        todos.append({'task': task, 'completed': False})
        save_todos(todos)
        print(f'Task "{task}" added!')
    else:
        print("Task cannot be empty.")

# List all tasks with their status
def list_todos():
    if not todos:
        print("No tasks available.")
    else:
        print("\nYour To-Do List:")
        for idx, todo in enumerate(todos, start=1):
            status = "✔" if todo['completed'] else "✘"
            print(f"{idx}. [{status}] {todo['task']}")
        print()  # Extra new line for better spacing

# Mark a task as completed by task number
def mark_completed():
    list_todos()
    try:
        task_num = int(input("Enter the task number to mark as completed: "))
        if 1 <= task_num <= len(todos):
            todos[task_num - 1]['completed'] = True
            save_todos(todos)
            print(f"Task {task_num} marked as completed!")
        else:
            print("Invalid task number.")
    except ValueError:
        print("Please enter a valid number.")

# Delete a task from the list by task number
def delete_todo():
    list_todos()
    try:
        task_num = int(input("Enter the task number to delete: "))
        if 1 <= task_num <= len(todos):
            deleted_task = todos.pop(task_num - 1)
            save_todos(todos)
            print(f'Task "{deleted_task["task"]}" deleted!')
        else:
            print("Invalid task number.")
    except ValueError:
        print("Please enter a valid number.")

# Display the menu of options
def menu():
    print("\nTo-Do List Menu:")
    print("1. Add a task")
    print("2. List all tasks")
    print("3. Mark a task as completed")
    print("4. Delete a task")
    print("5. Exit")

todos = load_todos()

# Main loop to display the menu and handle user input
while True:
    menu()
    choice = input("\nEnter your choice: ").strip()

    if choice == '1':
        add_todo()
    elif choice == '2':
        list_todos()
    elif choice == '3':
        mark_completed()
    elif choice == '4':
        delete_todo()
    elif choice == '5':
        print("Goodbye!")
        break
    else:
        print("Invalid choice. Please enter a number between 1 and 5.")